dev:
    - synth input port # linux qsynth
    - timidity port 0
    - loopmidi
    - loopbe
    - fluidsynth-midi
    - bassmidi driver (port a)
    #- qjackctl
    # helm will autoconnect
    - microsoft midi mapper # lowest preference
