dev:
    - synth input port # linux qsynth
    - timidity port 0
    - loopmidi
    - loopbe
    - fluidsynth-midi
    - fluid-synth
    - bassmidi driver (port a)
    # helm will autoconnect
    - microsoft midi mapper # lowest preference
    - midi in
    - hexter
    - virtual raw midi # carla
    - virmidi # linux virtual midi
    - qjackctl

